### ISSUE TITLE
#TODO LIST

### ISSUE THREAD

**Issue by gagangulyani** [gagangulyani/Psych-Up#1]
**The following is to be done to the site ordered with respect to priority (from highest to lowest):** 
- [x] Index
- [x] Sign Up
- [x] Login
- [x] User Profile
- [x] Followers
- [x] Following
- [x] Sign Up Admin (secret link)
- [x] Admin Dashboard (Edit User and Quiz from DB)
- [x] Add Questions for Quiz [Admin]
- [x] Edit Questions for Quiz [Admin]
- [x] Remove Questions for Quiz [Admin]
- [x] Remove Players from Quiz [Admin]
- [x] View Players [Admin]
- [x] Leaderboard ~Timeline~ (Displaying Users recent game scores)
- [x] Play Quiz
- [x] About -> Why  
- [x] About -> How 
- [x] About -> Who (made this site)
- [x] Get in touch with us (Contact)
